### ISSUE TITLE
ICL Architecture Diagram (Channel Directory)

### ISSUE THREAD

**Issue by shujingliew** [edi3/edi3-icl#26]
Agree with Dr Wang (China) that the Channel Directory will indicate centralised architecture. Suggest to remove the Channel Directory and indicate Route API in each ICL node instead.

**Comment by monkeypants** [comment]
I didn't read the diagram to mean the Chanel Directory was a central hub, perhaps @onthebreeze can comment on that. I do agree that each ICL node should be responsible for implementing it's own routing (meaning, the sender should decide how to send), and I also agree that a centralised component is not appropriate.

I read the diagram to mean that, in an abstract sense, routing table information was shared in an organised way. Perhaps it could be a central registry (I agree that would be a bad idea), or it could be a mutually agreed, decentralised blockchain mechanism. Or it could be a collaborative process of human communication. There is a question about *how* to distribute routing table information, but also a question *if* we actually need to do that. In other words:

* Should each country freely organise their routing tables any way they see fit, with **private routing**.
* or, should the routing tables be published, and should changes be  orchestrated, **orchestrated routing**.

There could be good arguments either way.  Private routing tables seems reasonable because it reflects what countries are going to do anyhow. Which channels they use to send what messages to whom is a matter of their own policy. They might want to be in control of how they route messages, give their own policies precedence over policies of the group.

On the other hand, "orchestrated routing" tables might help to avoid confusion and mistakes, and make it easier to change operating arrangements in a coordinated way. For example, if there are multiple possible routes that a message could take, which one should the sender use? does the receiver actually care? If there is an agreement to replace one mechanism with a new one, how is that change made without disrupting continuous operation?

Perhaps the need for orchestration will be low during early stages of development, when the topology is simple and/or rarely changing. Over time, if the topology becomes complex, or needs to change frequently, there may be some benefit in propagating change in a coordinated way.

**Comment by onthebreeze** [comment]
I've removed it from the diagram and from the API list.  

We can discuss later (maybe a version 2) how increasingly complex routing rules are managed.
